<?php

namespace Svn\TbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentReasonRepository extends EntityRepository
{
}
